name: Push to Alibaba Cloud ACR Personal

on:
  push:
    branches: [ main ]

env:
  ACR_REGISTRY: "crpi-i0xx8prfn3q76xh5.cn-hangzhou.personal.cr.aliyuncs.com"
  NAMESPACE: "image-proxy"
  IMAGE_NAME: "temp"  # 替换为您的镜像名称
  IMAGE_TAG: "latest"      # 或使用 ${{ github.sha }} 作为动态标签

jobs:
  push-to-acr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to ACR Personal
        run: |
          echo "Xgt@8541372" | docker login ${{ env.ACR_REGISTRY }} \
            -u "javaplugin" \
            --password-stdin

      - name: Build and Push
        run: |
          docker build -t ${{ env.ACR_REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
          docker push ${{ env.ACR_REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
